2021-09-05 08:05:21,790 ERROR: Exception on /index [GET] [in /home/zaldi_admn/bevii-env/lib/python3.7/site-packages/flask/app.py:1455]
Traceback (most recent call last):
  File "/home/zaldi_admn/bevii-env/lib/python3.7/site-packages/flask/app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/zaldi_admn/bevii-env/lib/python3.7/site-packages/flask/app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/zaldi_admn/bevii-env/lib/python3.7/site-packages/flask/app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/zaldi_admn/bevii-env/lib/python3.7/site-packages/flask/app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/zaldi_admn/bevii-env/lib/python3.7/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/home/zaldi_admn/bevii/app/main/routes.py", line 69, in index
    prev_url=prev_url)
  File "/home/zaldi_admn/bevii-env/lib/python3.7/site-packages/flask/templating.py", line 150, in render_template
    ctx.app,
  File "/home/zaldi_admn/bevii-env/lib/python3.7/site-packages/flask/templating.py", line 128, in _render
    rv = template.render(context)
  File "/home/zaldi_admn/bevii-env/lib/python3.7/site-packages/jinja2/environment.py", line 1304, in render
    self.environment.handle_exception()
  File "/home/zaldi_admn/bevii-env/lib/python3.7/site-packages/jinja2/environment.py", line 925, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/zaldi_admn/bevii/app/templates/index.html", line 2, in top-level template code
    {% import 'bootstrap/wtf.html' as wtf %}
  File "/home/zaldi_admn/bevii/app/templates/base.html", line 1, in top-level template code
    {% extends 'bootstrap/base.html' %}
  File "/home/zaldi_admn/bevii-env/lib/python3.7/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 1, in top-level template code
    {% block doc -%}
  File "/home/zaldi_admn/bevii-env/lib/python3.7/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 4, in block 'doc'
    {%- block html %}
  File "/home/zaldi_admn/bevii-env/lib/python3.7/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 20, in block 'html'
    {% block body -%}
  File "/home/zaldi_admn/bevii-env/lib/python3.7/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 23, in block 'body'
    {% block content -%}
  File "/home/zaldi_admn/bevii/app/templates/base.html", line 77, in block 'content'
    {% block app_content %}{% endblock %}
  File "/home/zaldi_admn/bevii/app/templates/index.html", line 11, in block 'app_content'
    {% include '_post.html' %}
  File "/home/zaldi_admn/bevii/app/templates/_post.html", line 33, in top-level template code
    <img src="{{ url_for('images', filename='uploads/' + post.image + '.sm.png') }}" class="img-thumbnail" />
  File "/home/zaldi_admn/bevii-env/lib/python3.7/site-packages/flask/helpers.py", line 338, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "/home/zaldi_admn/bevii-env/lib/python3.7/site-packages/flask/helpers.py", line 326, in url_for
    endpoint, values, method=method, force_external=external
  File "/home/zaldi_admn/bevii-env/lib/python3.7/site-packages/werkzeug/routing.py", line 2305, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'images' with values ['filename']. Did you mean 'main.messages' instead?
2021-09-05 08:05:30,002 ERROR: Exception on /index [GET] [in /home/zaldi_admn/bevii-env/lib/python3.7/site-packages/flask/app.py:1455]
Traceback (most recent call last):
  File "/home/zaldi_admn/bevii-env/lib/python3.7/site-packages/flask/app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/zaldi_admn/bevii-env/lib/python3.7/site-packages/flask/app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/zaldi_admn/bevii-env/lib/python3.7/site-packages/flask/app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/zaldi_admn/bevii-env/lib/python3.7/site-packages/flask/app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/zaldi_admn/bevii-env/lib/python3.7/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/home/zaldi_admn/bevii/app/main/routes.py", line 69, in index
    prev_url=prev_url)
  File "/home/zaldi_admn/bevii-env/lib/python3.7/site-packages/flask/templating.py", line 150, in render_template
    ctx.app,
  File "/home/zaldi_admn/bevii-env/lib/python3.7/site-packages/flask/templating.py", line 128, in _render
    rv = template.render(context)
  File "/home/zaldi_admn/bevii-env/lib/python3.7/site-packages/jinja2/environment.py", line 1304, in render
    self.environment.handle_exception()
  File "/home/zaldi_admn/bevii-env/lib/python3.7/site-packages/jinja2/environment.py", line 925, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/zaldi_admn/bevii/app/templates/index.html", line 2, in top-level template code
    {% import 'bootstrap/wtf.html' as wtf %}
  File "/home/zaldi_admn/bevii/app/templates/base.html", line 1, in top-level template code
    {% extends 'bootstrap/base.html' %}
  File "/home/zaldi_admn/bevii-env/lib/python3.7/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 1, in top-level template code
    {% block doc -%}
  File "/home/zaldi_admn/bevii-env/lib/python3.7/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 4, in block 'doc'
    {%- block html %}
  File "/home/zaldi_admn/bevii-env/lib/python3.7/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 20, in block 'html'
    {% block body -%}
  File "/home/zaldi_admn/bevii-env/lib/python3.7/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 23, in block 'body'
    {% block content -%}
  File "/home/zaldi_admn/bevii/app/templates/base.html", line 77, in block 'content'
    {% block app_content %}{% endblock %}
  File "/home/zaldi_admn/bevii/app/templates/index.html", line 11, in block 'app_content'
    {% include '_post.html' %}
  File "/home/zaldi_admn/bevii/app/templates/_post.html", line 33, in top-level template code
    <img src="{{ url_for('images', filename='uploads/' + post.image + '.sm.png') }}" class="img-thumbnail" />
  File "/home/zaldi_admn/bevii-env/lib/python3.7/site-packages/flask/helpers.py", line 338, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "/home/zaldi_admn/bevii-env/lib/python3.7/site-packages/flask/helpers.py", line 326, in url_for
    endpoint, values, method=method, force_external=external
  File "/home/zaldi_admn/bevii-env/lib/python3.7/site-packages/werkzeug/routing.py", line 2305, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'images' with values ['filename']. Did you mean 'main.messages' instead?
2021-09-05 08:29:21,210 INFO: Microblog startup [in /home/zaldi_admn/bevii/app/__init__.py:89]
2021-09-05 08:32:07,207 INFO: Microblog startup [in /home/zaldi_admn/bevii/app/__init__.py:89]
2021-09-05 08:39:31,688 INFO: Microblog startup [in /home/zaldi_admn/bevii/app/__init__.py:89]
2021-09-05 08:43:00,735 INFO: Microblog startup [in /home/zaldi_admn/bevii/app/__init__.py:89]
2021-09-05 08:43:42,478 ERROR: Exception on /index [POST] [in /home/zaldi_admn/bevii-env/lib/python3.7/site-packages/flask/app.py:1455]
Traceback (most recent call last):
  File "/home/zaldi_admn/bevii-env/lib/python3.7/site-packages/flask/app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/zaldi_admn/bevii-env/lib/python3.7/site-packages/flask/app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/zaldi_admn/bevii-env/lib/python3.7/site-packages/flask/app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/zaldi_admn/bevii-env/lib/python3.7/site-packages/flask/app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/zaldi_admn/bevii-env/lib/python3.7/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/home/zaldi_admn/bevii/app/main/routes.py", line 47, in index
    Image.open(f).save(file_path)
  File "/home/zaldi_admn/bevii-env/lib/python3.7/site-packages/PIL/Image.py", line 2232, in save
    fp = builtins.open(filename, "w+b")
PermissionError: [Errno 13] Permission denied: '/opt/bevii/static/images/uploads/73856a44-4994-4e3d-8e27-429ba326fc9b.png'
2021-09-05 09:08:49,934 INFO: Microblog startup [in /home/zaldi_admn/bevii/app/__init__.py:89]
2021-09-05 11:08:25,809 INFO: Microblog startup [in /home/zaldi_admn/bevii/app/__init__.py:89]
2021-09-05 11:13:15,872 INFO: Microblog startup [in /home/zaldi_admn/bevii/app/__init__.py:89]
2021-09-05 11:14:42,575 INFO: Microblog startup [in /home/zaldi_admn/bevii/app/__init__.py:89]
2021-09-12 08:17:57,847 INFO: Microblog startup [in /home/zaldi_admn/bevii/app/__init__.py:89]
